version: "3.9"
services:
  urllb:
    build: .
    ports:
      - "3000:3000"
    links:
      - postgres
    profiles:
      - urllb
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
